
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackGround from "@/components/Background";
import { Toaster } from "sonner";
import { RecruiterProvider } from "@/Context/RecruiterContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Beta AI",
  description: "Generated by Beta Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RecruiterProvider>
          <BackGround>
            <Toaster />
            {children}
          </BackGround>
        </RecruiterProvider>
      </body>
    </html>
  );
}
