# Generated by Django 5.1.7 on 2025-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_job_name_resume_instutut_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_resume',
            field=models.JSONField(default=dict),
        ),
    ]
