# Generated by Django 5.1.7 on 2025-03-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resume_parsed_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
