# Generated by Django 5.1.7 on 2025-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
